### PR TITLE
Fix unmount

### PR DESCRIPTION
**Pull request by Iskander508**
fix for issue with unmount not running useEffect cleanup: https://github.com/wojtekmaj/enzyme-adapter-react-17/issues/12

### CODE REVIEW

**Comment by vdwijngaert** [comment]
Would be helpful if this pull request was merged :)

**Comment by MikeMcMahon** [comment]
we are using this library as well and it would be very useful

**Comment by gisaklement** [comment]
Hi @wojtekmaj 
I found your adapter today 🥳  and it seems like the only things that's blocking our pipeline is this PR 🙂 
Any chance this pull request can be merged? 

Thank you so much helping us out!

**Comment by gisaklement** [comment]
Nevermind I just saw your [comment here](https://github.com/wojtekmaj/enzyme-adapter-react-17/issues/12#issuecomment-786789978)

> I'm afraid this will need to wait for an official package to be resolved

Thank you anyway though for this package!!

**Comment by wojtekmaj** [comment]
@gisaklement I started discussing this change in a PR that adds official React 17 adapter this package is based on. Let's see how it goes.

**Comment by gisaklement** [comment]
> @gisaklement I started discussing this change in a PR that adds official React 17 adapter this package is based on. Let's see how it goes.

Thank you so much!! I appreciate it 🙂

**Comment by wojtekmaj** [comment]
Looks like we won't get an official response anytime soon. Screw this then. @Iskander508 Please kindly rebase your branch off current master, or allow edits from maintainers, so I could check if this doesn't break anything, since tests were added recently.

**Comment by Iskander508** [comment]
> Looks like we won't get an official response anytime soon. Screw this then. @Iskander508 Please kindly rebase your branch off current master, or allow edits from maintainers, so I could check if this doesn't break anything, since tests were added recently.

Edits should be allowed already

**Comment by Iskander508** [comment]
rebased

**Comment by wojtekmaj** [comment]
Thanks so much.

Interestingly this doesn't seem to affect neither positively nor negatively any unit tests originally added to Enzyme.

Let's go for it.

**Comment by gisaklement** [comment]
Again, thank you very much 🙂

**Pull request merged**
