### PR TITLE
Add support for OffscreenComponent

### PR DESCRIPTION
**Pull request by wojtekmaj**

### CODE REVIEW

**Comment by Hypnosphi** [comment]
@wojtekmaj looks like your repo is missing a babel config. `yarn build` just copies files from `src` as is

**Comment by wojtekmaj** [comment]
Seems unrelated to this PR to me; anyway, that's how Babel is configured for enzyme-adapter-react-16.

**Comment by Hypnosphi** [comment]
It makes me unable to test it

**Comment by Hypnosphi** [comment]
> that's how Babel is configured for enzyme-adapter-react-16.

Nope, they do have babelrc: https://github.com/enzymejs/enzyme/blob/master/packages/enzyme-adapter-react-16/.babelrc

**Comment by Hypnosphi** [comment]
Ok, I've managed to do it by tweaking my `transformIgnorePatterns`. It mostly works, but fails with `Enzyme Internal Error: unknown node with tag undefined`. if Suspense has more than one child. Minimal reproduction case:

```js
import {configure, mount} from 'enzyme'
import Adapter from '@wojtekmaj/enzyme-adapter-react-17'
import {Suspense} from 'react'

configure({adapter: new Adapter()})

test('test', () => {
  mount(
    <Suspense fallback="">
      <div />
      <div />
    </Suspense>,
  )
})
```

**Comment by Hypnosphi** [comment]
Another issue: `.debug()` never shows the children of `Suspense`, only `<Suspense mode="visible" />`:

```js
console.log(
    mount(
      <Suspense fallback="">
        <div />
      </Suspense>,
    ).debug(),
  )
```

logs
```
 console.log
    <Suspense fallback="">
      <Suspense mode="visible" />
    </Suspense>

```

**Comment by wojtekmaj** [comment]
I edited the code to get up to speed with https://github.com/enzymejs/enzyme/pull/2430. Should be better now, but still some edge cases.

**Comment by Hypnosphi** [comment]
@wojtekmaj thank you. Now it mostly works, but if `Suspense` has more than one child, only the first one is used:

```js
console.log(
    mount(
      <Suspense fallback="">
        <div />
        <div />
      </Suspense>,
    ).debug(),
  )
```

```
console.log
    <Suspense fallback="">
      <div />
    </Suspense>
```

**Comment by wojtekmaj** [comment]
Interesting insight. Would you mind sharing it in the PR I linked?

 I'm mostly clueless to be honest and I'm only providing an early preview of the adapter so the people that don't do especially crazy stuff can go on with React 17 update without being blocked by Enzyme.

**Comment by Hypnosphi** [comment]
@wojtekmaj looks like these changes weren't built before releasing `0.3.0`. `build/detectFiberTags` doesn't include `OffscreenComponent` while `src/detectFiberTags` does

**Comment by Hypnosphi** [comment]
@wojtekmaj looks like these changes weren't built before releasing `0.3.0`

**Comment by wojtekmaj** [comment]
Oops, you're correct.

**Pull request merged**
